// Code generated by Prismic. DO NOT EDIT.

import HeroSection from "./HeroSection";
import ProductGrid from "./ProductGrid";

export const components = {
	hero_section: HeroSection,
	product_grid: ProductGrid
};