// Code generated by Prismic. DO NOT EDIT.

import HeroSection from "./HeroSection";
import ProductGrid from "./ProductGrid";
import TeamGrid from "./TeamGrid";
import TextAndImage from "./TextAndImage";
import VideoBlock from "./VideoBlock";

export const components = {
	hero_section: HeroSection,
	product_grid: ProductGrid,
	team_grid: TeamGrid,
	text_and_image: TextAndImage,
	video_block: VideoBlock
};